apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: true
    uid: tempo
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: prometheus
      nodeGraph:
        enabled: true
      search:
        hide: false
      lokiSearch:
        datasourceUid: ''
      tracesToLogsV2:
        datasourceUid: ''

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://otel-collector:8889
    uid: prometheus
    jsonData:
      httpMethod: GET
